name: Node.js Package

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm ci
          (cd ./packages/block-avatar;pwd;npm ci)
          (cd ./packages/block-button;pwd;npm ci)
          (cd ./packages/block-divider;pwd;npm ci)
          (cd ./packages/block-heading;pwd;npm ci)
          (cd ./packages/block-html;pwd;npm ci)
          (cd ./packages/block-image;pwd;npm ci)
          (cd ./packages/block-spacer;pwd;npm ci)
          (cd ./packages/block-text;pwd;npm ci)
          (cd ./packages/document-core;pwd;npm ci)
          (cd ./packages/editor-sample;pwd;npm ci)
          (cd ./packages/email-builder;pwd;npm ci)
      - run: npx eslint .
      - run: npx prettier . --check
      - run: npm test
      - run: ./node_modules/.bin/tsc --noEmit
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
